### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by godber** [planetarypy/planetary_test_data#1]
The intent of this package is to provide a framework to systematically list and test as many planetary data types as possible.  Not only should these products be enumerated, but their test values (e.g. label entries, pixel values) should also be stored in this module.

We have started a list of Missions, Instruments, products and our level of support here:

http://planetaryimage.readthedocs.org/en/latest/supported_planetary_image_types.html

I envision initial implementation of this package to be an extension of the `get_test_data.py` and `data.json` code I wrote for `gdal_pds`:
- https://github.com/godber/gdal_pds/blob/master/get_test_data.py
- https://github.com/godber/gdal_pds/blob/master/data.json

We would extend `data.json` to define additional keys to store expected test results and this file would be used as a source for acceptance testing for every mission product supported by PlanetaryPy.  Ultimately it is impractical to include mission data in the main testsuite for the `PlanetaryPy` software, this module is intended to bridge that gap.

**Comment by godber** [comment]
It might make sense to use (perhaps optionally) AstroPy's `astropy.util.data` modules:

http://astropy.readthedocs.org/en/latest/utils/#file-downloads

**Comment by godber** [comment]
This comment contains and example JSON snippet for data driven tests https://github.com/planetarypy/planetaryimage/issues/10#issuecomment-111843679

**Comment by percurnicus** [comment]
Start off by implementing the simplest `data.json` that contains a single Pancam product like:

``` json
{
    "1p190678905erp64kcp2600l8c1.img": {
        "url": "http://pds-geosciences.wustl.edu/mer/mer1-m-pancam-2-edr-sci-v1/mer1pc_0xxx/data/sol0704/1p190678905erp64kcp2600l8c1.img",
        "instrument": "Pancam",
        "opens": "True"
    },
}
```

Then write the downloader, `get_mission_data.py` that looks for the file at the relative path `tests/mission_data/data.json`.  If it exists, use the existing file.  If it doesn't exist, place the default `data.json` at that location, create the `mission_data` subdirectory if necessary.  If `tests/` exists, create the `mission_data` directory within it, if it does not exist, just create the `mission_data` directory in the present directory.

After the `data.json` file is in place, then load that `json` file and loop over the top level keys which should all be product names, test to see if the product already exists in the `mission_data` directory if it does, go onto the next one, if it does not then retrieve the file located at the `url` subkey and place it in the `mission_data` directory.

When including `data.json` make sure to use `package_data`, see: 
- https://docs.python.org/2/distutils/setupscript.html
- http://stackoverflow.com/questions/13307408/python-packaging-data-files-are-put-properly-in-tar-gz-file-but-are-not-install

**Comment by percurnicus** [comment]
Follow the `console_scripts` example here:
- https://github.com/planetarypy/pdsview/blob/master/setup.py
- Also http://click.pocoo.org/4/setuptools/

You may use click to implement your CLI if you want, though it may not be necessary at this point since we are not taking any arguments or options yet.

**Comment by godber** [comment]
Done!  Looks great!
