### ISSUE TITLE
Copy data.json

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/planetary_test_data#15]
Create mode to copy the data.json file. There should be a way to just copy a subset of the data.json by ``tags``. Eventually there should be a way to copy by other categories like instrument, mission, etc. but that is beyond the scope of this issue.

**Comment by tjslezak** [comment]
What type of subset are you imagining? I think instrument/mission tags would be the most natural and useful way to collect a subset.

**Comment by percurnicus** [comment]
In data.json, there are some entries with key-value pair ``"tags": "['core']"``. The created data.json should consist of just those tags (by default). The user should also be able to specify to copy the entire data.json. These are the features I plan to implement to fix this issue. You can see in the ``TODO`` in the README we plan to create ways of downloading the files based on categories like mission and instrument but not yet implemented. The same will go for copying the data.json.

---------------------

The reason for copying the data.json is to gives projects the ability to add their own test files to the copied data.json. And the reason for copying just a subset is to make it simpler and direct to add images as needed. For example, in pdsspect you can add the SSI images to the internal data.json so those images are available for testing. This is a much more efficient than adding more images to the planetary_test_data core (which I think has a sufficient number of images).

**Comment by percurnicus** [comment]
Mainly as a reminder to myself, we need to improve the contributing documentation in all affiliated projects so this is clear to other developers.

**Comment by percurnicus** [comment]
Fixed in #20
