### ISSUE TITLE
Download images by instrument

### ISSUE THREAD

**Issue by percurnicus** [planetarypy/planetary_test_data#19]
Place a tag to choose to download images by instrument name. It will probably be good add a mission option as well but this will require adding "mission" keys to each image section in data.json.

**Comment by tjslezak** [comment]
Depending on your intent and purposes for this - including "Target" keys might be useful. Most spacecraft missions (Voyager/New Horizons/Cassini/Galileo/etc..) collect observations of multiple planetary bodies.

**Comment by percurnicus** [comment]
I think that is beyond the scope of the project. The point is to provide potential planetary science python projects with common set of test images. The Instrument and mission flags are more for a convenience if someone creates a project for a specific mission or instrument, in which case they can just use the mission or instrument flag to get the desired images rather than creating their own data.json. Otherwise, projects for general planetary use that need images outside the core should create their own data.json, using images from the base data.json ideally.

**Comment by percurnicus** [comment]
Fixed in #28
