### ISSUE TITLE
Update data.json to contain full set of data

### ISSUE THREAD

**Issue by godber** [planetarypy/planetary_test_data#3]
Update the full `data.json` so it contains data products found here:

https://travis-ci.org/planetarypy/planetary_test_data/builds/70276183

**Comment by percurnicus** [comment]
I don't see any data products...Only a Travis CI that something failed

**Comment by godber** [comment]
My bad, this was the URL I meant to post:

http://planetaryimage.readthedocs.org/en/latest/supported_planetary_image_types.html

You are working on this already AFAIK.  Of course the failing travisCI is your other ticket.  :)

**Comment by godber** [comment]
This does a good job of addressing this ticket: https://github.com/planetarypy/planetary_test_data/pull/6
