### ISSUE TITLE
Fails in Python3

### ISSUE THREAD

**Issue by godber** [planetarypy/planetary_test_data#4]
This doesn't work in Python 3, check this out:

https://travis-ci.org/planetarypy/planetary_test_data/jobs/70276185

Don't forget, before you push your branch, you should be running `make test-all`.

**Comment by percurnicus** [comment]
Im having trouble running `make test-all`. I keep getting this error:

error: Operation not permitted

ERROR: FAIL could not package project - v = InvocationError('/home/pbvarga1/Workspace/planetary_test_data/venv_osx/bin/python /home/pbvarga1/Workspace/planetary_test_data/setup.py sdist --formats=zip --dist-dir /home/pbvarga1/Workspace/planetary_test_data/.tox/dist (see /home/pbvarga1/Workspace/planetary_test_data/.tox/log/tox-0.log)', 1)

Any ideas on how to fix?
